# Generated by Django 3.0.2 on 2020-01-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='college',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='player',
            name='mobile_number',
            field=models.BigIntegerField(default=0),
        ),
    ]
