# Generated by Django 3.0.2 on 2020-02-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nth', '0002_auto_20200118_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
