# Generated by Django 3.0.2 on 2020-02-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nth', '0004_auto_20200203_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='last_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
