# Generated by Django 3.0.2 on 2020-02-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nth', '0006_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='level',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
    ]
