# Generated by Django 3.0.3 on 2020-02-24 17:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nth', '0007_auto_20200221_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='reg_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
